image: maven:latest

# Define the stages that the jobs will run in
stages:
  - test
  - build
  - deploy

# Maven test job
test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  script:
    - mvn javadoc:javadoc # Generate Javadoc using Maven plugin

# GitLab Pages deployment job
deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r target/apidocs/* public/javadoc
  artifacts:
    paths:
      - public
  only:
    - master
